import { PropertyResponse, PropertyCategory, PropertyStatus } from '@shared/property';

export const demoProperties: PropertyResponse[] = [
  {
    id: 'prop-1',
    title: 'Luxury Downtown Apartment',
    description: 'Modern furnished apartment with city views',
    category: PropertyCategory.FURNISHED_APARTMENT,
    status: PropertyStatus.AVAILABLE,
    address: '123 Main St, Downtown',
    price: 2500,
    currency: 'USD',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    furnished: true,
    amenities: ['WiFi', 'Parking', 'Gym'],
    images: [],
    contactEmail: 'contact@demo.com',
    contactPhone: '+1-555-0123',
    created_by: 'demo@aiscraper.com',
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-20T14:45:00Z'
  },
  {
    id: 'prop-2',
    title: 'Family House with Garden',
    description: 'Spacious family home with private garden',
    category: PropertyCategory.FURNISHED_HOUSE,
    status: PropertyStatus.RENTED,
    address: '456 Oak Avenue, Suburbs',
    price: 3500,
    currency: 'USD',
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    furnished: true,
    amenities: ['Garden', 'Garage', 'Fireplace'],
    images: [],
    contactEmail: 'contact@demo.com',
    contactPhone: '+1-555-0124',
    created_by: 'demo@aiscraper.com',
    created_at: '2024-01-12T09:15:00Z',
    updated_at: '2024-01-20T16:20:00Z'
  },
  {
    id: 'prop-3',
    title: 'Business Traveler Suite',
    description: 'Fully serviced apartment for business travelers',
    category: PropertyCategory.SERVICED_APARTMENT,
    status: PropertyStatus.AVAILABLE,
    address: '789 Business District',
    price: 1800,
    currency: 'USD',
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    furnished: true,
    amenities: ['WiFi', 'Concierge', 'Business Center'],
    images: [],
    contactEmail: 'contact@demo.com',
    contactPhone: '+1-555-0125',
    created_by: 'demo@aiscraper.com',
    created_at: '2024-01-18T11:00:00Z',
    updated_at: '2024-01-20T11:00:00Z'
  },
  {
    id: 'prop-4',
    title: 'Executive Penthouse',
    description: 'Premium penthouse with panoramic views',
    category: PropertyCategory.FURNISHED_APARTMENT,
    status: PropertyStatus.MAINTENANCE,
    address: '321 High Street, City Center',
    price: 4500,
    currency: 'USD',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    furnished: true,
    amenities: ['Balcony', 'Premium Appliances', 'Valet'],
    images: [],
    contactEmail: 'contact@demo.com',
    contactPhone: '+1-555-0126',
    created_by: 'demo@aiscraper.com',
    created_at: '2024-01-16T14:30:00Z',
    updated_at: '2024-01-20T18:15:00Z'
  },
  {
    id: 'prop-5',
    title: 'Corporate Housing Unit',
    description: 'Professional serviced apartment with amenities',
    category: PropertyCategory.SERVICED_APARTMENT,
    status: PropertyStatus.AVAILABLE,
    address: '654 Corporate Plaza',
    price: 2200,
    currency: 'USD',
    bedrooms: 2,
    bathrooms: 1,
    area: 1000,
    furnished: true,
    amenities: ['WiFi', 'Laundry', 'Meeting Room'],
    images: [],
    contactEmail: 'contact@demo.com',
    contactPhone: '+1-555-0127',
    created_by: 'demo@aiscraper.com',
    created_at: '2024-01-14T08:45:00Z',
    updated_at: '2024-01-20T12:30:00Z'
  }
];
